name: Allure report

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./api
      - name: ls current
        run: ls
      - name: ls api
        run: ls ./api
      - name: ls api report
        run: ls ./api/allure-results
      - name: Copy report
        uses: canastro/copy-action@0.0.2
        with:
          source: ./api/target/allure-results
          target: ./api
